NTP wait loop for taildns

diff --git a/taildns.d/taildns b/taildns.d/taildns
--- a/taildns.d/taildns
+++ b/taildns.d/taildns
@@ -13,6 +13,19 @@ if [ "$cachemode" = "tmp" ]; then
 	taildnsfilesuffix="-cache"
 fi
 
+ntpwaitcount=0
+# Wait for NTP before starting
+while [ "$(nvram get ntp_ready)" -eq 0 ] && [ "$ntpwaitcount" -lt 600 ]; do
+	ntpwaitcount="$((ntpwaitcount + 30))"
+	logger -st "taildns" "Waiting for NTP to sync..." "$WARN"
+	sleep 30
+done
+
+if [ "$ntpwaitcount" -ge 600 ]; then
+	logger -st "taildns" "NTP failed to sync after 10 minutes - please check immediately!"
+	exit 1
+fi
+
 /jffs/addons/uiDivStats.d/taildns.d/taildnstotal"$taildnsfilesuffix" &
 
 while true; do
